services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt/:ro
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    networks:
      - skynet
    restart: always

networks:
  skynet:
    external: True